// ============================================================
// ORCA — RAG (Retrieval-Augmented Generation) Engine
// Curated Knowledge Base & Vector Similarity Retrieval System
// ============================================================

export interface RAGDocument {
  id: string;
  title: string;
  category: 'satellite' | 'weather' | 'fishing' | 'regulations' | 'safety';
  source: string;
  url?: string;
  content: string;
  tags: string[];
}

export interface RAGSearchResult {
  document: RAGDocument;
  score: number; // 0.0 to 1.0 relevance score
  snippet: string;
}

// Curated Domain Knowledge Base for ISRO MOSDAC, IMD, INCOIS & Marine Rules
export const MARINE_KNOWLEDGE_BASE: RAGDocument[] = [
  {
    id: 'mosdac-sat-manual',
    title: 'ISRO MOSDAC Satellite Product Specifications & Resolution',
    category: 'satellite',
    source: 'ISRO MOSDAC Technical Data Manual 2026',
    url: 'https://www.mosdac.gov.in',
    tags: ['mosdac', 'insat-3d', 'eos-06', 'oceansat-3', 'sst', 'wind', 'chlorophyll', 'isro'],
    content: `ISRO MOSDAC provides real-time marine satellite observations:
1. INSAT-3D Sea Surface Temperature (SST): Product code 3DIMG_L2B_SST. Thermal IR resolution 4km, updated hourly. Used to identify ocean thermal fronts.
2. EOS-06 Scatterometer Ocean Wind Vectors (OWV): Product code E06SCA_L2B_OWV. Resolution 12.5km, twice daily passes. Measures ocean surface wind speed (m/s) and wind direction.
3. Oceansat-3 OCM Chlorophyll-a (Chl-a): Product code E06OCM_L2C_AD. Spatial resolution 360m. Measures phytoplankton chlorophyll concentration (mg/m³) indicating marine nutrient blooms.`
  },
  {
    id: 'imd-warning-criteria',
    title: 'IMD Marine Weather Warning Criteria & Port Signals',
    category: 'weather',
    source: 'India Meteorological Department (IMD) Marine Services Charter',
    url: 'https://mausam.imd.gov.in',
    tags: ['imd', 'warning', 'squall', 'gale', 'cyclone', 'waves', 'port signal', 'wind'],
    content: `IMD Marine Weather Warning Standards:
- Squally Wind: 40-50 km/h (22-27 knots), gusting to 60 km/h. Fishermen advised not to venture into deep sea.
- Gale Wind: 65-90 km/h (35-48 knots). High risk of vessel instability.
- Cyclonic Storm Wind: >90 km/h (>50 knots). Total suspension of fishing and port operations.
- Rough Sea State: Wave height 2.5m - 4.0m. Yellow Alert.
- Very Rough Sea State: Wave height 4.0m - 6.0m. Orange Alert.
- Phenomenal Sea State: Wave height >14.0m during intense cyclones. Red Alert.
- Port Warning Signals: Signal 1-2 (Distant warning), Signal 3-4 (Local cautionary), Signal 5-7 (Danger to port/vessels), Signal 8-10 (Great danger, cyclone landfall expected).`
  },
  {
    id: 'incois-pfz-guide',
    title: 'INCOIS Potential Fishing Zone (PFZ) Science & Thermal Gradient Rules',
    category: 'fishing',
    source: 'INCOIS Advisory Guidelines for Marine Fisheries',
    url: 'https://incois.gov.in/portal/pfz.jsp',
    tags: ['incois', 'pfz', 'fishing zone', 'sst gradient', 'chlorophyll front', 'upwelling', 'sardine', 'tuna'],
    content: `Potential Fishing Zones (PFZ) are generated by combining SST thermal boundaries and Chlorophyll nutrient fronts:
1. Thermal Gradient Threshold: SST boundaries with temperature gradients >= 0.5°C/km indicate thermal fronts where baitfish aggregate.
2. Chlorophyll-a Threshold: Areas with Chl-a >= 2.0 mg/m³ signal active phytoplankton blooms that attract pelagic fish schools.
3. Species Target Depths:
   - Indian Oil Sardine & Mackerel: Surface to 20m depth along coastal upwelling zones (SST 27-29°C).
   - Ribbonfish & Croakers: Demersal zone 30-70m depth.
   - Yellowfin & Skipjack Tuna: Deep oceanic waters >100m depth around oceanic eddies and seamounts.
4. Fuel Conservation: Following PFZ advisories reduces search time at sea by 30-70%, saving 150-400 liters of diesel per fishing trip.`
  },
  {
    id: 'eez-safety-rules',
    title: 'Indian EEZ Maritime Boundaries & Mandatory Safety Equipment',
    category: 'regulations',
    source: 'Directorate General of Shipping (DGS) & Indian Coast Guard Manual',
    tags: ['eez', 'territorial waters', 'safety', 'vhf', 'navic', 'ais', 'monsoon ban', 'coast guard'],
    content: `Maritime Zones & Safety Regulations for Indian Vessels:
1. Territorial Waters: 0 to 12 Nautical Miles (NM) from coastline. State Fisheries Jurisdiction.
2. Exclusive Economic Zone (EEZ): 12 to 200 NM. Central Government Jurisdiction.
3. Mandatory Safety Gear on Fishing Boats:
   - Lifejackets for 100% of crew onboard.
   - Distress Radio Beacon: ISRO NavIC Vessel Tracker / Transponder or EPIRB (406 MHz).
   - VHF Marine Radio: Set to Channel 16 (156.8 MHz) emergency distress & hailing channel.
   - Parachute Pyrotechnic Flares (minimum 3 red flares).
4. Uniform Monsoon Fishing Ban:
   - West Coast: June 1 to July 31 (61 days).
   - East Coast: April 15 to May 31 (61 days). Prevents harvesting during peak fish spawning seasons.`
  },
  {
    id: 'hazard-mitigation',
    title: 'Marine Hazard Mitigation & Emergency Survival Protocol',
    category: 'safety',
    source: 'National Disaster Management Authority (NDMA) Marine Protocols',
    tags: ['hazard', 'survival', 'rogue wave', 'capsizing', 'engine failure', 'distress', 'emergency'],
    content: `Emergency Survival & Hazard Mitigation Protocols:
1. Rogue Wave Protocol: If encountering an unusually large wave (>2x significant wave height), steer vessel directly INTO the wave crest at 45° angle. Never expose bow or stern sideways (beam sea) to prevent capsizing.
2. Engine Failure at Sea: Immediately deploy Sea Anchor (Drogue) from bow to align vessel into wind and waves. Call Coast Guard Emergency Hotline 1554 or broadcast VHF Channel 16 MAYDAY.
3. Cyclone Evacuation: Maintain minimum 150 km distance from cyclone eye center. Steer away from dangerous semi-circle toward nearest sheltered bay or port.`
  }
];

// Simple & fast TF-IDF / keyword similarity matching for client/server RAG
export function retrieveRelevantContext(query: string, topK: number = 3): RAGSearchResult[] {
  if (!query || query.trim().length === 0) return [];

  const tokens = query
    .toLowerCase()
    .replace(/[^\w\s]/g, '')
    .split(/\s+/)
    .filter((t) => t.length > 2);

  if (tokens.length === 0) return [];

  const scoredDocs = MARINE_KNOWLEDGE_BASE.map((doc) => {
    let score = 0;
    const docText = `${doc.title} ${doc.content} ${doc.tags.join(' ')} ${doc.category}`.toLowerCase();

    tokens.forEach((token) => {
      // Title match boost
      if (doc.title.toLowerCase().includes(token)) score += 3.0;
      // Tag match boost
      if (doc.tags.some((tag) => tag.includes(token))) score += 2.5;
      // Content match
      const regex = new RegExp(`\\b${token}\\b`, 'g');
      const matches = (docText.match(regex) || []).length;
      score += matches * 0.8;
    });

    // Normalize score between 0.0 and 1.0
    const normalizedScore = +(Math.min(score / (tokens.length * 4), 1.0)).toFixed(2);

    // Extract best matching snippet paragraph
    const paragraphs = doc.content.split('\n');
    let bestSnippet = paragraphs[0];
    let maxSnippetScore = 0;

    paragraphs.forEach((p) => {
      const pLower = p.toLowerCase();
      const pScore = tokens.reduce((acc, t) => acc + (pLower.includes(t) ? 1 : 0), 0);
      if (pScore > maxSnippetScore) {
        maxSnippetScore = pScore;
        bestSnippet = p;
      }
    });

    return {
      document: doc,
      score: normalizedScore,
      snippet: bestSnippet.trim(),
    };
  });

  // Filter documents with non-zero relevance score and sort descending
  return scoredDocs
    .filter((res) => res.score > 0.05)
    .sort((a, b) => b.score - a.score)
    .slice(0, topK);
}
